<a href="https://colab.research.google.com/github/gudiya-archi/python-Data-Science/blob/main/Python_pandas01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is Pandas

# pandas is a fast, powerful, flexible and easy to use open source data analysis and mainpulation tool , built on top of the python programming language.

# Pandas Series

# A Pandas Series is like a column in a table. it is a 1D array holding data of any type

In [4]:
import numpy as np
import pandas as pd

# Series from lists

In [5]:
# string
country = ['India','USA','Japan','China','Germany']
pd.Series(country)

0      India
1        USA
2      Japan
3      China
4    Germany
dtype: object

In [23]:
# integers
runs = [13,24,56,78,100]
pd.Series(runs)

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [7]:
# custom index

marks = [67,57,89,100]
subjects = ['math','science','english','hindi']

pd.Series(marks,index=subjects)

math        67
science     57
english     89
hindi      100
dtype: int64

In [9]:
# setting a name
marks = pd.Series(marks,index=subjects, name  ='archi ke marks')
marks

math        67
science     57
english     89
hindi      100
Name: archi ke marks, dtype: int64

# Series from dict

In [24]:
marks = {
    'math':67,
    'science':57,
    'english':89,
    'hindi':100

    }


marks_series = pd.Series(marks, name = 'archi ke marks')
marks_series

math        67
science     57
english     89
hindi      100
Name: archi ke marks, dtype: int64

# Series Attributes

In [25]:
# size
marks_series

math        67
science     57
english     89
hindi      100
Name: archi ke marks, dtype: int64

In [13]:
# size
marks_series.size

4

In [14]:
# dtype
marks_series.dtype

dtype('int64')

In [15]:
# name
marks_series.name

'archi ke marks'

In [16]:
# is_unique
marks_series.is_unique

True

In [19]:
marks_series.is_unique
pd.Series([1,1,2,3]).is_unique

False

In [20]:
# index
marks_series.index

Index(['math', 'science', 'english', 'hindi'], dtype='object')

In [26]:
# integers
runs = [13,24,56,78,100]
runs_ser = pd.Series(runs)

In [27]:
runs_ser.index

RangeIndex(start=0, stop=5, step=1)

In [28]:
type(runs_ser.index)

pandas.core.indexes.range.RangeIndex

In [29]:
# values
marks_series.values

array([ 67,  57,  89, 100])

In [30]:
type(marks_series.values )

numpy.ndarray