<a href="https://colab.research.google.com/github/gudiya-archi/python-Data-Science/blob/main/Python_Pandas_date_and_time03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

# Timestamp Object
* time stamps reference particular moments in time
* (e.g, Oct 24th,2022 at 7.00pm)

# Creating timestamp objects

* creating a timestamp
* variations
* only year
* using text
* providing time also

In [2]:
# creating a timestamp
pd.Timestamp('2026/07/4')

Timestamp('2026-07-04 00:00:00')

In [3]:
type(pd.Timestamp('2026/07/4'))

pandas._libs.tslibs.timestamps.Timestamp

In [4]:
# variations
print(pd.Timestamp('2026-07-4'))
print(pd.Timestamp('2026/7/4'))

2026-07-04 00:00:00
2026-07-04 00:00:00

In [5]:
print(pd.Timestamp('2026, 7, 4'))

2026-07-04 00:00:00

# only year

In [6]:
# only year
pd.Timestamp('2026')

Timestamp('2026-01-01 00:00:00')

# using text

In [7]:
# using text
pd.Timestamp('5th January 2026')

Timestamp('2026-01-05 00:00:00')

In [8]:
# providing time also
pd.Timestamp(2026, 1, 5)

Timestamp('2026-01-05 00:00:00')

In [9]:
# providing time also
pd.Timestamp(2026, 1, 5, 9,21 )

Timestamp('2026-01-05 09:21:00')

In [10]:
pd.Timestamp('5th January 2026 9:21PM')

Timestamp('2026-01-05 21:21:00')

In [11]:
pd.Timestamp('5th January 2026 9:21AM')

Timestamp('2026-01-05 09:21:00')

In [12]:
pd.Timestamp(2026/1/5)

Timestamp('1970-01-01 00:00:00.000000405')

# using datetime.datetime object
# import datetime as dt

In [13]:
# using datetimme.datetime object
import datetime as dt
my_date = dt.datetime(2026, 1, 5, 9, 21)
pd.Timestamp(my_date)

Timestamp('2026-01-05 09:21:00')

In [14]:
pd.Timestamp(dt.datetime(2026, 1, 5, 9, 21))

Timestamp('2026-01-05 09:21:00')

In [15]:
# using datetimme.datetime object
x = pd.Timestamp(dt.datetime(2026, 1, 5, 9, 21))
x

Timestamp('2026-01-05 09:21:00')

In [16]:
# fetching attributes
print(x.year)
print(x.month)
print(x.day)
print(x.hour)
print(x.minute)
print(x.second)

2026
1
5
9
21
0

# Why separates objects to handle data and time when python already has datatime functionality?

* syntax wise datetime is very convenient
* but the performance takes a hit while working with huge data. list vs numpy array
* the weaknesses of Python's datetime formate inspired the Numpy team to add a set of native time series data type to Numpy
* the datetime 64 dtype encodes dates as 64-bit integer, and thus allows arrays of dates to be represented very compactly.

In [17]:
import numpy as np
date = np.array('2026-07-04', dtype=np.datetime64)
date

array('2026-07-04', dtype='datetime64[D]')

In [18]:
date + np.arange(12)

array(['2026-07-04', '2026-07-05', '2026-07-06', '2026-07-07',
       '2026-07-08', '2026-07-09', '2026-07-10', '2026-07-11',
       '2026-07-12', '2026-07-13', '2026-07-14', '2026-07-15'],
      dtype='datetime64[D]')

* Because of the uniform type in Numpy datetime64 arrays , this type of opertion can be accomplished much more quickly than if we were working directly with python datatime objects , especially as arrys get large

* pandas timestamp object combines the ease-of-use of python datetimewith the efficient storage and vectorized interface of numpy.datetime64

* from  a group of these timestamp objects, pandas can construct a Datetimeindex that can be used to index data in a series or dataframe

# DatetimeIndex Object

# A Collection of pandas timestamp
* from string
* using python datetime object
* using pd.timestamps
* using datetimeindex as series index

In [19]:
# from strings
pd.DatetimeIndex(['2026-07-04', '2025-09-05', '2024-08-06'])

DatetimeIndex(['2026-07-04', '2025-09-05', '2024-08-06'], dtype='datetime64[ns]', freq=None)

In [20]:
# from strings
pd.DatetimeIndex(['2026-07-04', '2025-09-05', '2024-08-06'])  [0]

Timestamp('2026-07-04 00:00:00')

In [21]:
type(pd.DatetimeIndex(['2026-07-04', '2025-09-05', '2024-08-06']))

pandas.core.indexes.datetimes.DatetimeIndex

In [22]:
# using python datetime object
pd.DatetimeIndex([dt.datetime(2026, 7, 4), dt.datetime(2025, 9, 5), dt.datetime(2024, 8, 6)])

DatetimeIndex(['2026-07-04', '2025-09-05', '2024-08-06'], dtype='datetime64[ns]', freq=None)

In [23]:
# using pd.timestamps
pd.DatetimeIndex([pd.Timestamp(2026, 7, 4), pd.Timestamp(2025, 9, 5), pd.Timestamp(2024, 8, 6)])

DatetimeIndex(['2026-07-04', '2025-09-05', '2024-08-06'], dtype='datetime64[ns]', freq=None)

In [ ]:
# using pd.timestamps
pd.DatetimeIndex([pd.Timestamp(2026, 7, 4), pd.Timestamp(2025, 9, 5), pd.Timestamp(2024, 8, 6)])

In [24]:
# using pd.timestamps
dt_index = pd.DatetimeIndex([pd.Timestamp(2026, 7, 4), pd.Timestamp(2025, 9, 5), pd.Timestamp(2024, 8, 6)])

In [25]:
# using datetimeindex as series index
pd.Series(data=[1,2,3], index=dt_index)

2026-07-04    1
2025-09-05    2
2024-08-06    3
dtype: int64

# date_range function

# generate daily dates in a given range

In [26]:
# generate daily dates in a given range
pd.date_range(start='2026-07-01', end='2026-07-31', freq='D')

DatetimeIndex(['2026-07-01', '2026-07-02', '2026-07-03', '2026-07-04',
               '2026-07-05', '2026-07-06', '2026-07-07', '2026-07-08',
               '2026-07-09', '2026-07-10', '2026-07-11', '2026-07-12',
               '2026-07-13', '2026-07-14', '2026-07-15', '2026-07-16',
               '2026-07-17', '2026-07-18', '2026-07-19', '2026-07-20',
               '2026-07-21', '2026-07-22', '2026-07-23', '2026-07-24',
               '2026-07-25', '2026-07-26', '2026-07-27', '2026-07-28',
               '2026-07-29', '2026-07-30', '2026-07-31'],
              dtype='datetime64[ns]', freq='D')

In [27]:
# generate daily dates in a given range
pd.date_range(start='2026-07-01', end='2026-08-28', freq='D')

DatetimeIndex(['2026-07-01', '2026-07-02', '2026-07-03', '2026-07-04',
               '2026-07-05', '2026-07-06', '2026-07-07', '2026-07-08',
               '2026-07-09', '2026-07-10', '2026-07-11', '2026-07-12',
               '2026-07-13', '2026-07-14', '2026-07-15', '2026-07-16',
               '2026-07-17', '2026-07-18', '2026-07-19', '2026-07-20',
               '2026-07-21', '2026-07-22', '2026-07-23', '2026-07-24',
               '2026-07-25', '2026-07-26', '2026-07-27', '2026-07-28',
               '2026-07-29', '2026-07-30', '2026-07-31', '2026-08-01',
               '2026-08-02', '2026-08-03', '2026-08-04', '2026-08-05',
               '2026-08-06', '2026-08-07', '2026-08-08', '2026-08-09',
               '2026-08-10', '2026-08-11', '2026-08-12', '2026-08-13',
               '2026-08-14', '2026-08-15', '2026-08-16', '2026-08-17',
               '2026-08-18', '2026-08-19', '2026-08-20', '2026-08-21',
               '2026-08-22', '2026-08-23', '2026-08-24', '2026-08-25',
               '2026-08-26', '2026-08-27', '2026-08-28'],
              dtype='datetime64[ns]', freq='D')

In [28]:
# generate daily dates in a given range
pd.date_range(start='2026-07-01', end='2026-08-28', freq='2D')

DatetimeIndex(['2026-07-01', '2026-07-03', '2026-07-05', '2026-07-07',
               '2026-07-09', '2026-07-11', '2026-07-13', '2026-07-15',
               '2026-07-17', '2026-07-19', '2026-07-21', '2026-07-23',
               '2026-07-25', '2026-07-27', '2026-07-29', '2026-07-31',
               '2026-08-02', '2026-08-04', '2026-08-06', '2026-08-08',
               '2026-08-10', '2026-08-12', '2026-08-14', '2026-08-16',
               '2026-08-18', '2026-08-20', '2026-08-22', '2026-08-24',
               '2026-08-26', '2026-08-28'],
              dtype='datetime64[ns]', freq='2D')

In [30]:
# alternate days in a given range
pd.date_range(start='2026-07-01', end='2026-08-28', freq='3D')

DatetimeIndex(['2026-07-01', '2026-07-04', '2026-07-07', '2026-07-10',
               '2026-07-13', '2026-07-16', '2026-07-19', '2026-07-22',
               '2026-07-25', '2026-07-28', '2026-07-31', '2026-08-03',
               '2026-08-06', '2026-08-09', '2026-08-12', '2026-08-15',
               '2026-08-18', '2026-08-21', '2026-08-24', '2026-08-27'],
              dtype='datetime64[ns]', freq='3D')

# B ---> business days

In [31]:
# B---> business days
pd.date_range(start='2026-07-01', end='2026-08-28', freq='B')

DatetimeIndex(['2026-07-01', '2026-07-02', '2026-07-03', '2026-07-06',
               '2026-07-07', '2026-07-08', '2026-07-09', '2026-07-10',
               '2026-07-13', '2026-07-14', '2026-07-15', '2026-07-16',
               '2026-07-17', '2026-07-20', '2026-07-21', '2026-07-22',
               '2026-07-23', '2026-07-24', '2026-07-27', '2026-07-28',
               '2026-07-29', '2026-07-30', '2026-07-31', '2026-08-03',
               '2026-08-04', '2026-08-05', '2026-08-06', '2026-08-07',
               '2026-08-10', '2026-08-11', '2026-08-12', '2026-08-13',
               '2026-08-14', '2026-08-17', '2026-08-18', '2026-08-19',
               '2026-08-20', '2026-08-21', '2026-08-24', '2026-08-25',
               '2026-08-26', '2026-08-27', '2026-08-28'],
              dtype='datetime64[ns]', freq='B')

# W --> one week per day

In [32]:
# W --> one week per day
pd.date_range(start='2026-07-01', end='2026-08-28', freq='W')

DatetimeIndex(['2026-07-05', '2026-07-12', '2026-07-19', '2026-07-26',
               '2026-08-02', '2026-08-09', '2026-08-16', '2026-08-23'],
              dtype='datetime64[ns]', freq='W-SUN')

In [34]:
pd.date_range(start='2026-07-01', end='2026-08-28', freq='W-THU')

DatetimeIndex(['2026-07-02', '2026-07-09', '2026-07-16', '2026-07-23',
               '2026-07-30', '2026-08-06', '2026-08-13', '2026-08-20',
               '2026-08-27'],
              dtype='datetime64[ns]', freq='W-THU')

# H ---> Hourly date (factor)

In [33]:
# H --> hourly date (factor)
pd.date_range(start='2026-07-01', end='2026-08-28', freq='H')

/tmp/ipykernel_7908/427762530.py:2: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range(start='2026-07-01', end='2026-08-28', freq='H')

DatetimeIndex(['2026-07-01 00:00:00', '2026-07-01 01:00:00',
               '2026-07-01 02:00:00', '2026-07-01 03:00:00',
               '2026-07-01 04:00:00', '2026-07-01 05:00:00',
               '2026-07-01 06:00:00', '2026-07-01 07:00:00',
               '2026-07-01 08:00:00', '2026-07-01 09:00:00',
               ...
               '2026-08-27 15:00:00', '2026-08-27 16:00:00',
               '2026-08-27 17:00:00', '2026-08-27 18:00:00',
               '2026-08-27 19:00:00', '2026-08-27 20:00:00',
               '2026-08-27 21:00:00', '2026-08-27 22:00:00',
               '2026-08-27 23:00:00', '2026-08-28 00:00:00'],
              dtype='datetime64[ns]', length=1393, freq='h')

In [35]:
pd.date_range(start='2026-07-01', end='2026-08-28', freq='6H')

/tmp/ipykernel_7908/2491477144.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range(start='2026-07-01', end='2026-08-28', freq='6H')

DatetimeIndex(['2026-07-01 00:00:00', '2026-07-01 06:00:00',
               '2026-07-01 12:00:00', '2026-07-01 18:00:00',
               '2026-07-02 00:00:00', '2026-07-02 06:00:00',
               '2026-07-02 12:00:00', '2026-07-02 18:00:00',
               '2026-07-03 00:00:00', '2026-07-03 06:00:00',
               ...
               '2026-08-25 18:00:00', '2026-08-26 00:00:00',
               '2026-08-26 06:00:00', '2026-08-26 12:00:00',
               '2026-08-26 18:00:00', '2026-08-27 00:00:00',
               '2026-08-27 06:00:00', '2026-08-27 12:00:00',
               '2026-08-27 18:00:00', '2026-08-28 00:00:00'],
              dtype='datetime64[ns]', length=233, freq='6h')

# M --> month end

In [38]:
#  M --> month end
pd.date_range(start='2026-07-01', end='2026-08-28', freq='M')

/tmp/ipykernel_7908/1550541124.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range(start='2026-07-01', end='2026-08-28', freq='M')

DatetimeIndex(['2026-07-31'], dtype='datetime64[ns]', freq='ME')

# MS --> year start

In [39]:
pd.date_range(start='2026-07-01', end='2026-08-28', freq='MS')

DatetimeIndex(['2026-07-01', '2026-08-01'], dtype='datetime64[ns]', freq='MS')

# A --> year end

In [41]:
pd.date_range(start='2026-07-01', end='2030-08-28', freq='A')

/tmp/ipykernel_7908/1222637715.py:1: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  pd.date_range(start='2026-07-01', end='2030-08-28', freq='A')

DatetimeIndex(['2026-12-31', '2027-12-31', '2028-12-31', '2029-12-31'], dtype='datetime64[ns]', freq='YE-DEC')

# using periods (number of results)

In [43]:
pd.date_range(start='2026-07-01', periods=25, freq='D')

DatetimeIndex(['2026-07-01', '2026-07-02', '2026-07-03', '2026-07-04',
               '2026-07-05', '2026-07-06', '2026-07-07', '2026-07-08',
               '2026-07-09', '2026-07-10', '2026-07-11', '2026-07-12',
               '2026-07-13', '2026-07-14', '2026-07-15', '2026-07-16',
               '2026-07-17', '2026-07-18', '2026-07-19', '2026-07-20',
               '2026-07-21', '2026-07-22', '2026-07-23', '2026-07-24',
               '2026-07-25'],
              dtype='datetime64[ns]', freq='D')

In [44]:
pd.date_range(start='2026-07-01', periods=25, freq='H')

/tmp/ipykernel_7908/1667190132.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range(start='2026-07-01', periods=25, freq='H')

DatetimeIndex(['2026-07-01 00:00:00', '2026-07-01 01:00:00',
               '2026-07-01 02:00:00', '2026-07-01 03:00:00',
               '2026-07-01 04:00:00', '2026-07-01 05:00:00',
               '2026-07-01 06:00:00', '2026-07-01 07:00:00',
               '2026-07-01 08:00:00', '2026-07-01 09:00:00',
               '2026-07-01 10:00:00', '2026-07-01 11:00:00',
               '2026-07-01 12:00:00', '2026-07-01 13:00:00',
               '2026-07-01 14:00:00', '2026-07-01 15:00:00',
               '2026-07-01 16:00:00', '2026-07-01 17:00:00',
               '2026-07-01 18:00:00', '2026-07-01 19:00:00',
               '2026-07-01 20:00:00', '2026-07-01 21:00:00',
               '2026-07-01 22:00:00', '2026-07-01 23:00:00',
               '2026-07-02 00:00:00'],
              dtype='datetime64[ns]', freq='h')

In [45]:
pd.date_range(start='2026-07-01', periods=25, freq='6H')

/tmp/ipykernel_7908/2441672011.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  pd.date_range(start='2026-07-01', periods=25, freq='6H')

DatetimeIndex(['2026-07-01 00:00:00', '2026-07-01 06:00:00',
               '2026-07-01 12:00:00', '2026-07-01 18:00:00',
               '2026-07-02 00:00:00', '2026-07-02 06:00:00',
               '2026-07-02 12:00:00', '2026-07-02 18:00:00',
               '2026-07-03 00:00:00', '2026-07-03 06:00:00',
               '2026-07-03 12:00:00', '2026-07-03 18:00:00',
               '2026-07-04 00:00:00', '2026-07-04 06:00:00',
               '2026-07-04 12:00:00', '2026-07-04 18:00:00',
               '2026-07-05 00:00:00', '2026-07-05 06:00:00',
               '2026-07-05 12:00:00', '2026-07-05 18:00:00',
               '2026-07-06 00:00:00', '2026-07-06 06:00:00',
               '2026-07-06 12:00:00', '2026-07-06 18:00:00',
               '2026-07-07 00:00:00'],
              dtype='datetime64[ns]', freq='6h')

In [46]:
pd.date_range(start='2026-07-01', periods=25, freq='M')

/tmp/ipykernel_7908/698339287.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  pd.date_range(start='2026-07-01', periods=25, freq='M')

DatetimeIndex(['2026-07-31', '2026-08-31', '2026-09-30', '2026-10-31',
               '2026-11-30', '2026-12-31', '2027-01-31', '2027-02-28',
               '2027-03-31', '2027-04-30', '2027-05-31', '2027-06-30',
               '2027-07-31', '2027-08-31', '2027-09-30', '2027-10-31',
               '2027-11-30', '2027-12-31', '2028-01-31', '2028-02-29',
               '2028-03-31', '2028-04-30', '2028-05-31', '2028-06-30',
               '2028-07-31'],
              dtype='datetime64[ns]', freq='ME')

# to_datetime function

# converts an existing objects to pandas timestamp / datetimeindex object

In [47]:
# simple series example
s = pd.Series(['2023/1/1','2022/1/1','2021/1/1'])

In [48]:
s

0    2023/1/1
1    2022/1/1
2    2021/1/1
dtype: object

In [49]:
# simple series example
s = pd.Series(['2023/1/1','2022/1/1','2021/1/1'])
pd.to_datetime(s)

0   2023-01-01
1   2022-01-01
2   2021-01-01
dtype: datetime64[ns]

In [50]:
pd.to_datetime(s).dt.year

0    2023
1    2022
2    2021
dtype: int32

In [51]:
pd.to_datetime(s).dt.month

0    1
1    1
2    1
dtype: int32

In [55]:
pd.to_datetime(s).dt.day

0    1
1    1
2    1
dtype: int32

In [54]:
pd.to_datetime(s).dt.day_name()

0      Sunday
1    Saturday
2      Friday
dtype: object

In [56]:
pd.to_datetime(s).dt.month_name()

0    January
1    January
2    January
dtype: object

In [58]:
# with error
s = pd.Series(['2023/1/1','2022/1/1','2021/130/1'])
s

0      2023/1/1
1      2022/1/1
2    2021/130/1
dtype: object

In [60]:
# pd.to_datetime(s)
pd.to_datetime(s, errors='coerce')

0   2023-01-01
1   2022-01-01
2          NaT
dtype: datetime64[ns]

In [61]:
# pd.to_datetime(s)
pd.to_datetime(s, errors='coerce').dt.month

0    1.0
1    1.0
2    NaN
dtype: float64