<a href="https://colab.research.google.com/github/gudiya-archi/python-Data-Science/blob/main/Python_Pandas_groupby_objects03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# session 19

* file name :
# deliveries

In [2]:
import numpy as np
import pandas as pd

In [3]:
ipl = pd.read_csv("/content/deliveries.csv")
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [4]:
ipl.shape

(179078, 21)

# find the top batsman with max no of runs

In [5]:
 ipl.groupby('batsman')['batsman_runs'].sum()

batsman
A Ashish Reddy     280
A Chandila           4
A Chopra            53
A Choudhary         25
A Dananjaya          4
                  ...
YV Takawale        192
Yashpal Singh       47
Younis Khan          3
Yuvraj Singh      2765
Z Khan             117
Name: batsman_runs, Length: 516, dtype: int64

In [6]:
 ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

# find the batsman with max no of sixes

In [7]:
ipl ['batsman_runs'] == 6

0         False
1         False
2         False
3         False
4         False
          ...
179073    False
179074    False
179075    False
179076    False
179077    False
Name: batsman_runs, Length: 179078, dtype: bool

In [8]:
ipl[ipl ['batsman_runs'] == 6]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
47,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,4,MC Henriques,S Dhawan,TM Head,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
75,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,13,2,Yuvraj Singh,MC Henriques,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
89,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,3,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
91,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,5,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178987,11415,2,Chennai Super Kings,Mumbai Indians,6,4,SR Watson,SK Raina,SL Malinga,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179048,11415,2,Chennai Super Kings,Mumbai Indians,16,1,DJ Bravo,SR Watson,SL Malinga,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179061,11415,2,Chennai Super Kings,Mumbai Indians,18,2,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179062,11415,2,Chennai Super Kings,Mumbai Indians,18,3,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179063,11415,2,Chennai Super Kings,Mumbai Indians,18,4,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [9]:
six = ipl[ipl ['batsman_runs'] == 6]
six

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
47,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,4,MC Henriques,S Dhawan,TM Head,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
75,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,13,2,Yuvraj Singh,MC Henriques,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
89,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,3,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
91,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,5,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178987,11415,2,Chennai Super Kings,Mumbai Indians,6,4,SR Watson,SK Raina,SL Malinga,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179048,11415,2,Chennai Super Kings,Mumbai Indians,16,1,DJ Bravo,SR Watson,SL Malinga,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179061,11415,2,Chennai Super Kings,Mumbai Indians,18,2,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179062,11415,2,Chennai Super Kings,Mumbai Indians,18,3,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179063,11415,2,Chennai Super Kings,Mumbai Indians,18,4,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [11]:
six = ipl[ipl ['batsman_runs'] == 6]
six.groupby('batsman')['batsman_runs']

In [12]:
six = ipl[ipl ['batsman_runs'] == 6]
six.groupby('batsman')['batsman_runs'].count()

batsman
A Ashish Reddy      15
A Choudhary          1
A Flintoff           2
A Hales              6
A Mishra             5
                  ...
Y Venugopal Rao     37
YK Pathan          161
YV Takawale          3
Yuvraj Singh       149
Z Khan               2
Name: batsman_runs, Length: 336, dtype: int64

In [13]:
six = ipl[ipl ['batsman_runs'] == 6]
six.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False)

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
                 ...
AN Ahmed            1
AD Mascarenhas      1
TA Boult            1
T Kohli             1
TS Mills            1
Name: batsman_runs, Length: 336, dtype: int64

In [16]:
six = ipl[ipl ['batsman_runs'] == 6]
six.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head(1)

batsman
CH Gayle    327
Name: batsman_runs, dtype: int64

In [15]:
six = ipl[ipl ['batsman_runs'] == 6]
six.groupby('batsman')['batsman_runs'].count().sort_values(ascending=False).head(1).index[0]

'CH Gayle'

# find batsman with most number of 4's ans 6's in last 5 overs

In [18]:
ipl [ipl['over'] >= 15]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
87,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,1,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
88,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,2,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
89,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,3,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
90,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,4,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
91,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,5,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [19]:
temp_df = ipl[ipl['over'] >= 15]
temp_df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
87,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,1,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
88,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,2,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
89,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,3,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
90,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,4,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
91,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,5,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [22]:
temp_df = ipl[ipl['over'] >= 15]
temp_df[(temp_df['batsman_runs'] == 4) | (temp_df['batsman_runs'] == 6)]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
87,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,1,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
89,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,3,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
91,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,5,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
101,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,17,3,Yuvraj Singh,DJ Hooda,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
105,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,18,1,DJ Hooda,Yuvraj Singh,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179052,11415,2,Chennai Super Kings,Mumbai Indians,16,5,SR Watson,DJ Bravo,SL Malinga,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
179061,11415,2,Chennai Super Kings,Mumbai Indians,18,2,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179062,11415,2,Chennai Super Kings,Mumbai Indians,18,3,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179063,11415,2,Chennai Super Kings,Mumbai Indians,18,4,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179071,11415,2,Chennai Super Kings,Mumbai Indians,19,6,RA Jadeja,SR Watson,JJ Bumrah,0,...,4,0,0,0,4,4,8,NaN,NaN,NaN

In [29]:
temp_df = ipl[ipl['over'] >= 15]
temp_df[(temp_df['batsman_runs'] == 4) | (temp_df['batsman_runs'] == 6)]
temp_df.groupby('batsman')['batsman'].count().sort_values(ascending=False)

batsman
MS Dhoni          1890
KA Pollard        1171
RG Sharma         1043
YK Pathan          906
RA Jadeja          864
                  ...
C Nanda              1
SE Bond              1
Sunny Gupta          1
U Kaul               1
V Pratap Singh       1
Name: batsman, Length: 471, dtype: int64

In [31]:
temp_df = ipl[ipl['over'] >= 15]
temp_df[(temp_df['batsman_runs'] == 4) | (temp_df['batsman_runs'] == 6)]
temp_df.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(1)

batsman
MS Dhoni    1890
Name: batsman, dtype: int64

In [33]:
temp_df = ipl[ipl['over'] >= 15]
temp_df[(temp_df['batsman_runs'] == 4) | (temp_df['batsman_runs'] == 6)]
temp_df.groupby('batsman')['batsman'].count().sort_values(ascending=False).head(1).index[0]

'MS Dhoni'

# find V Kohli's record against all teams

In [34]:
ipl[ipl['batsman'] == 'V Kohli']

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2590,12,1,Royal Challengers Bangalore,Mumbai Indians,1,2,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
2591,12,1,Royal Challengers Bangalore,Mumbai Indians,1,3,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2593,12,1,Royal Challengers Bangalore,Mumbai Indians,1,5,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2594,12,1,Royal Challengers Bangalore,Mumbai Indians,1,6,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2597,12,1,Royal Challengers Bangalore,Mumbai Indians,2,1,V Kohli,CH Gayle,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177522,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,7,V Kohli,AB de Villiers,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
177523,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,1,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
177524,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,2,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
177525,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,3,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
177527,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,5,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,0,0,0,V Kohli,caught,WP Saha

In [35]:
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2590,12,1,Royal Challengers Bangalore,Mumbai Indians,1,2,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
2591,12,1,Royal Challengers Bangalore,Mumbai Indians,1,3,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2593,12,1,Royal Challengers Bangalore,Mumbai Indians,1,5,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2594,12,1,Royal Challengers Bangalore,Mumbai Indians,1,6,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2597,12,1,Royal Challengers Bangalore,Mumbai Indians,2,1,V Kohli,CH Gayle,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177522,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,7,V Kohli,AB de Villiers,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
177523,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,1,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
177524,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,2,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
177525,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,3,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
177527,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,5,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,0,0,0,V Kohli,caught,WP Saha

In [36]:
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df.groupby('bowling_team')['batsman_runs'].sum()

bowling_team
Chennai Super Kings        749
Deccan Chargers            306
Delhi Capitals              66
Delhi Daredevils           763
Gujarat Lions              283
Kings XI Punjab            636
Kochi Tuskers Kerala        50
Kolkata Knight Riders      675
Mumbai Indians             628
Pune Warriors              128
Rajasthan Royals           370
Rising Pune Supergiant      83
Rising Pune Supergiants    188
Sunrisers Hyderabad        509
Name: batsman_runs, dtype: int64

In [37]:
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df.groupby('bowling_team')['batsman_runs'].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           749
1           Deccan Chargers           306
2            Delhi Capitals            66
3          Delhi Daredevils           763
4             Gujarat Lions           283
5           Kings XI Punjab           636
6      Kochi Tuskers Kerala            50
7     Kolkata Knight Riders           675
8            Mumbai Indians           628
9             Pune Warriors           128
10         Rajasthan Royals           370
11   Rising Pune Supergiant            83
12  Rising Pune Supergiants           188
13      Sunrisers Hyderabad           509

# create a function that can return the highest score of any batsman

In [38]:
ipl['batsman'] == 'V Kohli'

0         False
1         False
2         False
3         False
4         False
          ...
179073    False
179074    False
179075    False
179076    False
179077    False
Name: batsman, Length: 179078, dtype: bool

In [39]:
ipl[ipl['batsman'] == 'V Kohli']

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2590,12,1,Royal Challengers Bangalore,Mumbai Indians,1,2,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
2591,12,1,Royal Challengers Bangalore,Mumbai Indians,1,3,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2593,12,1,Royal Challengers Bangalore,Mumbai Indians,1,5,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2594,12,1,Royal Challengers Bangalore,Mumbai Indians,1,6,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2597,12,1,Royal Challengers Bangalore,Mumbai Indians,2,1,V Kohli,CH Gayle,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177522,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,7,V Kohli,AB de Villiers,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
177523,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,1,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
177524,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,2,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
177525,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,3,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
177527,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,5,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,0,0,0,V Kohli,caught,WP Saha

In [40]:
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2590,12,1,Royal Challengers Bangalore,Mumbai Indians,1,2,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
2591,12,1,Royal Challengers Bangalore,Mumbai Indians,1,3,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2593,12,1,Royal Challengers Bangalore,Mumbai Indians,1,5,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2594,12,1,Royal Challengers Bangalore,Mumbai Indians,1,6,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2597,12,1,Royal Challengers Bangalore,Mumbai Indians,2,1,V Kohli,CH Gayle,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177522,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,7,V Kohli,AB de Villiers,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
177523,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,1,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
177524,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,2,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
177525,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,3,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
177527,11345,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,5,V Kohli,AB de Villiers,K Ahmed,0,...,0,0,0,0,0,0,0,V Kohli,caught,WP Saha

In [41]:
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df.groupby('match_id')['batsman_runs'].sum()

match_id
12       62
17       28
20       64
27        0
30       10
         ..
11330     9
11333    13
11337    24
11340    25
11345    16
Name: batsman_runs, Length: 169, dtype: int64

In [42]:
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False)

match_id
626      113
620      109
611      108
595      100
11326    100
        ...
27         0
488        0
481        0
462        0
633        0
Name: batsman_runs, Length: 169, dtype: int64

In [43]:
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1)

match_id
626    113
Name: batsman_runs, dtype: int64

In [44]:
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).index[0]

np.int64(626)

In [45]:
temp_df = ipl[ipl['batsman'] == 'V Kohli']
temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]

np.int64(113)

In [46]:
def highest(batsman):
  temp_df = ipl[ipl['batsman'] == batsman]
  return temp_df.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1).values[0]

In [47]:
highest('V Kohli')

np.int64(113)

In [49]:
highest('DA Warner')

np.int64(126)